TestApplication/Controllers/LocalStorageWizard/LocalStorageWizardStep1Controller.cs
using Microsoft.AspNetCore.Mvc;
using TestApplication.ViewModel;

namespace TestApplication.Controllers.LocalStorageWizard
{
    public class LocalStorageWizardStep1Controller : Controller
    {
        public IActionResult Index()
        {
            var step1ViewModel = new Step1ViewModel();
            return View("~/Views/LocalStorageWizard/Step1.cshtml", step1ViewModel);
        }

        [HttpPost]
        public IActionResult Next(Step1ViewModel viewModel)
        {
            Validate(viewModel);

            if (!ModelState.IsValid)
            {
                return View("~/Views/LocalStorageWizard/Step1.cshtml", viewModel);
            }

            var step2viewModel = new Step2ViewModel();

            return View("~/Views/LocalStorageWizard/Step2.cshtml", step2viewModel);
        }

        private void Validate(Step1ViewModel viewModel)
        {
            if (string.IsNullOrEmpty(viewModel.Bear))
            {
                ModelState.AddModelError("Bear", "Please inform a type of bear");
            }
        }
    }
}

TestApplication/Controllers/LocalStorageWizard/LocalStorageWizardStep2Controller.cs
using Microsoft.AspNetCore.Mvc;
using TestApplication.ViewModel;

namespace TestApplication.Controllers.LocalStorageWizard
{
    public class LocalStorageWizardStep2Controller : Controller
    {
        public IActionResult Index()
        {
            var step2ViewModel = new Step2ViewModel();
            return View("~/Views/LocalStorageWizard/Step2.cshtml", step2ViewModel);
        }

        [HttpPost]
        public IActionResult Next(Step2ViewModel viewModel)
        {
            Validate(viewModel);

            if (!ModelState.IsValid)
            {
                return View("~/Views/LocalStorageWizard/Step2.cshtml", viewModel);
            }

            var step3viewModel = new Step3ViewModel();

            return View("~/Views/LocalStorageWizard/Step3.cshtml", step3viewModel);
        }

        private void Validate(Step2ViewModel viewModel)
        {
            if (string.IsNullOrEmpty(viewModel.Food))
            {
                ModelState.AddModelError("Food", "Please inform a food");
            }
        }
    }
}

TestApplication/Controllers/LocalStorageWizard/LocalStorageWizardStep3Controller.cs
using Microsoft.AspNetCore.Mvc;
using TestApplication.ViewModel;

namespace TestApplication.Controllers.LocalStorageWizard
{
    public class LocalStorageWizardStep3Controller : Controller
    {
        public IActionResult Index()
        {
            var step3ViewModel = new Step3ViewModel();
            return View("~/Views/LocalStorageWizard/Step3.cshtml", step3ViewModel);
        }

        [HttpPost]
        public IActionResult Next(Step3ViewModel viewModel)
        {
            Validate(viewModel);

            if (!ModelState.IsValid)
            {
                return View("~/Views/LocalStorageWizard/Step3.cshtml", viewModel);
            }

            var model = new WizardViewModel();

            return View("~/Views/LocalStorageWizard/Step4.cshtml", model);
        }

        private void Validate(Step3ViewModel viewModel)
        {
            if (string.IsNullOrEmpty(viewModel.TvShow))
            {
                ModelState.AddModelError("TvShow", "Please inform a TV Show");
            }
        }
    }
}

TestApplication/Controllers/LocalStorageWizard/LocalStorageWizardStep4Controller.cs
using Microsoft.AspNetCore.Mvc;
using TestApplication.ViewModel;

namespace TestApplication.Controllers.LocalStorageWizard
{
    public class LocalStorageWizardStep4Controller : Controller
    {

        [HttpPost]
        public IActionResult Validate(WizardViewModel viewModel)
        {
            ValidateModel(viewModel);

            if (!ModelState.IsValid)
            {
                return View("~/Views/LocalStorageWizard/Step4.cshtml", viewModel);
            }

            return View("~/Views/LocalStorageWizard/FinalStep.cshtml");
        }

        private void ValidateModel(WizardViewModel viewModel)
        {
            if (string.IsNullOrEmpty(viewModel.Bear) || viewModel.Bear.ToLower().CompareTo("black") != 0)
                ModelState.AddModelError("Bear", "Wrong! It is the Black Bear.");

            if(string.IsNullOrEmpty(viewModel.Food) || viewModel.Food.ToLower().CompareTo("beats") != 0)
                ModelState.AddModelError("Food", "Wrong! Bear eats beats.");

            if (string.IsNullOrEmpty(viewModel.TvShow) || viewModel.TvShow.ToLower().CompareTo("battlestar galactica") != 0)
                ModelState.AddModelError("TvShow", "Wrong! The best TV Show is Battlestar Galactica.");
        }
    }
}

TestApplication/Views/LocalStorageWizard/FinalStep.cshtml
<h1>All done, thanks!</h1>

<input type="button" value="Select another wizard" onclick="location.href='@Url.Action("", "Home")'" />

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/localStorageWizard/finalStep.js"></script>

TestApplication/Views/LocalStorageWizard/Step1.cshtml
@model TestApplication.ViewModel.Step1ViewModel

<form method="post" asp-controller="LocalStorageWizardStep1" asp-action="Next">
    <h1>Step 1</h1>
    
    <h3>Question, what type of bear is best?</h3>    
    <input id="bearTxt" name="bear" type="text" value="@Model.Bear" />
    <br />
    <br />
    <input type="submit" value="Next" />
</form>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/localStorageWizard/step1.js"></script>

TestApplication/Views/LocalStorageWizard/Step2.cshtml
@model TestApplication.ViewModel.Step2ViewModel

<form method="post" asp-controller="LocalStorageWizardStep2" asp-action="Next">
    <h1>Step 2</h1>
    
    <h3>What do bears eat?</h3>    
    <input id="foodTxt" name="food" type="text" value="@Model.Food" />
    <br />
    <br />
    <input type="button" onclick="location.href='@Url.Action("", "LocalStorageWizardStep1")'" value="Back" />
    <input type="submit" value="Next" />
</form>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/localStorageWizard/step2.js"></script>

TestApplication/Views/LocalStorageWizard/Step3.cshtml
@model TestApplication.ViewModel.Step3ViewModel

<form method="post" asp-controller="LocalStorageWizardStep3" asp-action="Next">
    <h1>Step 3</h1>
    
    <h3>What is the best TV Show?</h3>    
    <input id="tvShowTxt" name="tvShow" type="text" value="@Model.TvShow" />
    <br />
    <br />
    <input type="button" onclick="location.href='@Url.Action("", "LocalStorageWizardStep2")'" value="Back" />
    <input type="submit" value="Next" />
</form>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/localStorageWizard/step3.js"></script>

TestApplication/Views/LocalStorageWizard/Step4.cshtml
@model TestApplication.ViewModel.WizardViewModel

<form method="post" asp-controller="LocalStorageWizardStep4" asp-action="Validate">
    <h1>Step 4</h1>
    
    <h3>Your answers</h3>    
    <h4>Question, what type of bear is best?</h4>
    <p id="bear"></p>
    <span asp-validation-for="@Model.Bear"></span>    
    <input type="hidden" asp-for="@Model.Bear" id="bearHiddenInput" value="" />
    <br />

    <h4>What do bears eat?</h4>
    <p id="food"></p>
    <span asp-validation-for="@Model.Food" class="text-danger"></span>
    <input type="hidden" asp-for="@Model.Food" id="foodHiddenInput" value="" />
    <br />

    <h4>What is the best TV Show?</h4>
    <p id="tvShow"></p>
    <span asp-validation-for="@Model.TvShow" class="text-danger"></span>
    <input type="hidden" asp-for="@Model.TvShow" id="tvShowHiddenInput" value="" />
    
    <br />
    <br />
    <input type="button" onclick="location.href='@Url.Action("", "LocalStorageWizardStep3")'" value="Back" />
    <input type="submit" value="Validate" />
</form>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/localStorageWizard/step4.js"></script>